class SharedPrefsForThisApp {
  String EXCLUDED_CONTACTS = 'EXCLUDED_CONTACTS';
  String NUMBER_OF_CONTACTS_TO_DISPLAY = 'NUMBER_OF_CONTACTS_TO_DISPLAY';
  String FIRST_TIME_USER = 'FIRST_TIME_USER';
}
